version: "3.9" 
services: 
  mysql: 
    image: mysql:8.0 
    environment: 
      MYSQL_ROOT_PASSWORD: rootpassword 
      MYSQL_DATABASE: security_management_db 
      MYSQL_USER: user 
      MYSQL_PASSWORD: password 
    ports: 
      - "3306:3306" 
    volumes: 
      - mysql_data:/var/lib/mysql 
  backend: 
    build: ./backend 
    environment: 
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/security_management_db 
      SPRING_DATASOURCE_USERNAME: user 
      SPRING_DATASOURCE_PASSWORD: password 
    ports: 
      - "8080:8080" 
    depends_on: 
      - mysql 
  frontend: 
    build: ./frontend 
    ports: 
      - "80:80" 
    depends_on: 
volumes: 
  mysql_data: 
